more fixes..

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,7 +24,7 @@ matrix:
         env: PROJ=artoolkitplus OS=linux-x86_64
       - jdk: oraclejdk7
         os: linux
-        env: PROJ=opencv,chilitags,flandmark,openblas,mxnet,caffe OS=linux-x86_64
+        env: PROJ=opencv,chilitags,flandmark,openblas,mxnet,hdf5,caffe OS=linux-x86_64
       - jdk: oraclejdk7
         os: linux
         env: PROJ=cuda OS=linux-x86_64
@@ -37,9 +37,6 @@ matrix:
       - jdk: oraclejdk7
         os: linux
         env: PROJ=gsl OS=linux-x86_64
-      - jdk: oraclejdk7
-        os: linux
-        env: PROJ=hdf5 OS=linux-x86_64
       - jdk: oraclejdk7
         os: linux
         env: PROJ=leptonica,tesseract OS=linux-x86_64
@@ -67,7 +64,7 @@ matrix:
       - os: osx
         env: PROJ=artoolkitplus OS=macosx-x86_64
       - os: osx
-        env: PROJ=opencv,chilitags,flandmark,openblas,mxnet,caffe OS=macosx-x86_64
+        env: PROJ=opencv,chilitags,flandmark,openblas,mxnet,hdf5,caffe OS=macosx-x86_64
       - os: osx
         env: PROJ=cuda OS=macosx-x86_64
       - os: osx
@@ -85,8 +82,6 @@ matrix:
       - os: osx
         env: PROJ=libfreenect2 OS=macosx-x86_64
       - os: osx
-        env: PROJ=hdf5 OS=macosx-x86_64
-      - os: osx
         env: PROJ=liquidfun OS=macosx-x86_64
       - os: osx
         env: PROJ=llvm OS=macosx-x86_64
@@ -100,7 +95,6 @@ before_install:
    - mkdir ./buildlogs
    - git clone https://github.com/bytedeco/javacpp.git
    - cd javacpp
-   #- git checkout d7d6af2b4a2d5e5d3ea48cb27248e2f84a031fd2 
    - mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
    - cd ..
    - export PYTHON_BIN_PATH=$(which python) # For tensorflow
@@ -113,7 +107,7 @@ before_install:
         fi
         if [ "$OS" == "linux-x86_64" ]; then
           echo "starting docker"
-          docker run --privileged -d -ti -e "container=docker" -v $HOME/.m2/:/root/.m2/ -v $HOME/build/:/root/build/ -v /sys/fs/cgroup:/sys/fs/cgroup nvidia/cuda:8.0-cudnn6-devel-centos7 /usr/sbin/init > /dev/null
+          docker run --privileged -d -ti -e "container=docker" -v $HOME/.m2/:/root/.m2/ -v $TRAVIS_BUILD_DIR:/root/build/ -v /sys/fs/cgroup:/sys/fs/cgroup nvidia/cuda:8.0-cudnn6-devel-centos7 /usr/sbin/init > /dev/null
           DOCKER_CONTAINER_ID=$(docker ps | grep centos | awk '{print $1}')
           echo "container id is $DOCKER_CONTAINER_ID please wait while updates applied"
           docker exec -ti $DOCKER_CONTAINER_ID /bin/bash -xec "yum -y install epel-release" > /dev/null
@@ -153,9 +147,10 @@ install:
 script:
    - |
     echo "download dependencies" 
+    ls -ltr $TRAVIS_BUILD_DIR
     if [ "$TRAVIS_OS_NAME" == "osx" ]; then
       if [[ "$PROJ" =~ mxnet ]]; then 
-        export PKG_CONFIG_PATH=/Users/travis/build/vb216/javacpp-presets/opencv/cppbuild/macosx-x86_64/lib/pkgconfig
+        export PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR/javacpp-presets/opencv/cppbuild/macosx-x86_64/lib/pkgconfig
       fi 
       if [[ "$PROJ" =~ cuda ]] || [[ "$PROJ" =~ tensorflow ]] || [[ "$PROJ" =~ caffe ]]; then 
         echo "installing cuda.."
@@ -181,22 +176,20 @@ script:
     if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       DOCKER_CONTAINER_ID=$(docker ps | grep centos | awk '{print $1}')
       echo "container id is $DOCKER_CONTAINER_ID"
-      docker exec -ti $DOCKER_CONTAINER_ID /bin/bash -xec "cd /root/build/vb216/javacpp-presets;mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Djavacpp.platform=$OS -pl $PROJ"; export BUILD_STATUS=$?
+      docker exec -ti $DOCKER_CONTAINER_ID /bin/bash -xec "cd /root/build/javacpp-presets;mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Djavacpp.platform=$OS -pl $PROJ"; export BUILD_STATUS=$?
       echo "Build status $BUILD_STATUS"
       if [ $BUILD_STATUS -ne 0 ]; then  
         echo "Build Failed"
         return $BUILD_STATUS
       fi
     else	
-     echo "test Output" > ~/build/vb216/javacpp-presets/buildlogs/$PROJ.log
      #redirect tensorflow error log to an S3 artifact as its too verbose
      if [ "$PROJ" == *tensorflow* ]; then 
-       echo "redirecting tensorflow error output"
-       pwd
-       ls -ltr ~/build/vb216/javacpp-presets
-       ./ci/prog.sh $PROJ &
-       mvn clean install -Dmaven.javadoc.skip=true -Djavacpp.platform=$OS -l ~/build/vb216/javacpp-presets/buildlogs/$PROJ.log -pl $PROJ; export BUILD_STATUS=$?
-       tail -50 ~/build/vb216/javacpp-presets/buildlogs/$PROJ.log
+       #echo "redirecting tensorflow error output"
+       #./ci/prog.sh $PROJ &
+       #mvn clean install -Dmaven.javadoc.skip=true -Djavacpp.platform=$OS -l ~/build/vb216/javacpp-presets/buildlogs/$PROJ.log -pl $PROJ; export BUILD_STATUS=$?
+       mvn clean install -Dmaven.javadoc.skip=true -Djavacpp.platform=$OS -pl $PROJ; export BUILD_STATUS=$?
+       #tail -50 ~/build/vb216/javacpp-presets/buildlogs/$PROJ.log
      else
        mvn clean install -Dmaven.javadoc.skip=true -Djavacpp.platform=$OS -pl $PROJ; export BUILD_STATUS=$?
      fi
