* Upgrade presets for FFmpeg 5.0.1, DepthAI 2.15.2, OpenSSL 3.0.2

diff --git a/ffmpeg/ffmpeg.patch b/ffmpeg/ffmpeg.patch
--- a/ffmpeg/ffmpeg.patch
+++ b/ffmpeg/ffmpeg.patch
@@ -1,6 +1,7 @@
---- ffmpeg-5.0.orig/configure	2022-01-15 05:45:39.000000000 +1100
-+++ ffmpeg-5.0/configure	2022-01-19 13:18:21.151444791 +1100
-@@ -6532,7 +6532,7 @@
+diff -ruN ffmpeg-5.0.1/configure ffmpeg-5.0.1-patch/configure
+--- ffmpeg-5.0.1/configure	2022-04-04 23:40:22.000000000 +0900
++++ ffmpeg-5.0.1-patch/configure	2022-04-09 22:33:09.335670342 +0900
+@@ -6539,7 +6539,7 @@
  enabled libflite          && require libflite "flite/flite.h" flite_init $flite_extralibs
  enabled fontconfig        && enable libfontconfig
  enabled libfontconfig     && require_pkg_config libfontconfig fontconfig "fontconfig/fontconfig.h" FcInit
@@ -9,7 +10,7 @@
  enabled libfribidi        && require_pkg_config libfribidi fribidi fribidi.h fribidi_version_info
  enabled libglslang && { check_lib spirv_compiler glslang/Include/glslang_c_interface.h glslang_initialize_process \
                              -lglslang -lMachineIndependent -lOSDependent -lHLSL -lOGLCompiler -lGenericCodeGen \
-@@ -6555,8 +6555,7 @@
+@@ -6562,8 +6562,7 @@
  # Media SDK or Intel Media Server Studio, these don't come with
  # pkg-config support.  Instead, users should make sure that the build
  # can find the libraries and headers through other means.
@@ -19,7 +20,7 @@
  if enabled libmfx; then
     check_cc MFX_CODEC_VP9 "mfx/mfxvp9.h mfx/mfxstructures.h" "MFX_CODEC_VP9"
  fi
-@@ -6574,19 +6573,12 @@
+@@ -6581,19 +6580,12 @@
                                 { check_pkg_config libopencv opencv opencv2/core/core_c.h cvCreateImageHeader ||
                                   require libopencv opencv2/core/core_c.h cvCreateImageHeader -lopencv_core -lopencv_imgproc; } ||
                                 require_pkg_config libopencv opencv opencv/cxcore.h cvCreateImageHeader; }
@@ -41,7 +42,7 @@
  enabled libplacebo        && require_pkg_config libplacebo "libplacebo >= 4.192.0" libplacebo/vulkan.h pl_vulkan_create
  enabled libpulse          && require_pkg_config libpulse libpulse pulse/pulseaudio.h pa_context_new
  enabled librabbitmq       && require_pkg_config librabbitmq "librabbitmq >= 0.7.1" amqp.h amqp_new_connection
-@@ -6602,8 +6594,8 @@
+@@ -6609,8 +6601,8 @@
  enabled libsnappy         && require libsnappy snappy-c.h snappy_compress -lsnappy -lstdc++
  enabled libsoxr           && require libsoxr soxr.h soxr_create -lsoxr
  enabled libssh            && require_pkg_config libssh libssh libssh/sftp.h sftp_init
@@ -52,7 +53,7 @@
  enabled libsvtav1         && require_pkg_config libsvtav1 "SvtAv1Enc >= 0.8.4" EbSvtAv1Enc.h svt_av1_enc_init_handle
  enabled libtensorflow     && require libtensorflow tensorflow/c/c_api.h TF_Version -ltensorflow
  enabled libtesseract      && require_pkg_config libtesseract tesseract tesseract/capi.h TessBaseAPICreate
-@@ -6622,19 +6614,15 @@
+@@ -6629,19 +6621,15 @@
  
  enabled libvpx            && {
      enabled libvpx_vp8_decoder && {
@@ -72,7 +73,7 @@
              check_lib libvpx_vp9_encoder "vpx/vpx_encoder.h vpx/vp8cx.h" "vpx_codec_vp9_cx VPX_IMG_FMT_HIGHBITDEPTH" "-lvpx $libm_extralibs $pthreads_extralibs"
      }
      if disabled_all libvpx_vp8_decoder libvpx_vp9_decoder libvpx_vp8_encoder libvpx_vp9_encoder; then
-@@ -6643,14 +6631,14 @@
+@@ -6650,14 +6638,14 @@
  }
  
  enabled libwebp           && {
@@ -91,7 +92,7 @@
                               require_cpp_condition libx265 x265.h "X265_BUILD >= 70"
  enabled libxavs           && require libxavs "stdint.h xavs.h" xavs_encoder_encode "-lxavs $pthreads_extralibs $libm_extralibs"
  enabled libxavs2          && require_pkg_config libxavs2 "xavs2 >= 1.3.0" "stdint.h xavs2.h" xavs2_api_get
-@@ -6660,7 +6648,7 @@
+@@ -6667,7 +6655,7 @@
  enabled libzvbi           && require_pkg_config libzvbi zvbi-0.2 libzvbi.h vbi_decoder_new &&
                               { test_cpp_condition libzvbi.h "VBI_VERSION_MAJOR > 0 || VBI_VERSION_MINOR > 2 || VBI_VERSION_MINOR == 2 && VBI_VERSION_MICRO >= 28" ||
                                 enabled gpl || die "ERROR: libzvbi requires version 0.2.28 or --enable-gpl."; }
@@ -100,7 +101,14 @@
  enabled mbedtls           && { check_pkg_config mbedtls mbedtls mbedtls/x509_crt.h mbedtls_x509_crt_init ||
                                 check_pkg_config mbedtls mbedtls mbedtls/ssl.h mbedtls_ssl_init ||
                                 check_lib mbedtls mbedtls/ssl.h mbedtls_ssl_init -lmbedtls -lmbedx509 -lmbedcrypto ||
-@@ -6704,9 +6692,9 @@
+@@ -6705,15 +6693,13 @@
+                                die "ERROR: OpenMAX IL headers from raspberrypi/firmware not found"; } &&
+                              enable omx
+ enabled omx               && require_headers OMX_Core.h
+-enabled openssl           && { { check_pkg_config openssl "openssl >= 3.0.0" openssl/ssl.h OPENSSL_init_ssl &&
+-                                 { enabled gplv3 || ! enabled gpl || enabled nonfree || die "ERROR: OpenSSL >=3.0.0 requires --enable-version3"; }; } ||
+-                               { enabled gpl && ! enabled nonfree && die "ERROR: OpenSSL <3.0.0 is incompatible with the gpl"; } ||
++enabled openssl           && { 
                                 check_pkg_config openssl openssl openssl/ssl.h OPENSSL_init_ssl ||
                                 check_pkg_config openssl openssl openssl/ssl.h SSL_library_init ||
                                 check_lib openssl openssl/ssl.h OPENSSL_init_ssl -lssl -lcrypto ||
