* Upgrade presets for FFmpeg 6.0 (issue bytedeco/javacv#1693)

diff --git a/ffmpeg/ffmpeg.patch b/ffmpeg/ffmpeg.patch
--- a/ffmpeg/ffmpeg.patch
+++ b/ffmpeg/ffmpeg.patch
@@ -1,6 +1,7 @@
---- ffmpeg-5.1.2/configure	2022-09-01 04:58:25.000000000 +1000
-+++ ffmpeg-5.1.2-patch/configure	2023-01-05 14:31:56.359994464 +1100
-@@ -6523,7 +6523,7 @@
+diff -ruN ffmpeg-6.0/configure ffmpeg-6.0-patch/configure
+--- ffmpeg-6.0/configure	2023-02-28 05:43:45.000000000 +0900
++++ ffmpeg-6.0-patch/configure	2023-03-02 18:30:58.642611366 +0900
+@@ -6563,7 +6563,7 @@
  enabled jni               && { [ $target_os = "android" ] && check_headers jni.h && enabled pthreads || die "ERROR: jni not found"; }
  enabled ladspa            && require_headers "ladspa.h dlfcn.h"
  enabled lcms2             && require_pkg_config lcms2 "lcms2 >= 2.13" lcms2.h cmsCreateContext
@@ -9,7 +10,7 @@
  enabled libaribb24        && { check_pkg_config libaribb24 "aribb24 > 1.0.3" "aribb24/aribb24.h" arib_instance_new ||
                                 { enabled gpl && require_pkg_config libaribb24 aribb24 "aribb24/aribb24.h" arib_instance_new; } ||
                                 die "ERROR: libaribb24 requires version higher than 1.0.3 or --enable-gpl."; }
-@@ -6548,7 +6548,7 @@
+@@ -6588,7 +6588,7 @@
  enabled libflite          && require libflite "flite/flite.h" flite_init $flite_extralibs
  enabled fontconfig        && enable libfontconfig
  enabled libfontconfig     && require_pkg_config libfontconfig fontconfig "fontconfig/fontconfig.h" FcInit
@@ -18,20 +19,24 @@
  enabled libfribidi        && require_pkg_config libfribidi fribidi fribidi.h fribidi_version_info
  enabled libglslang && { check_lib spirv_compiler glslang/Include/glslang_c_interface.h glslang_initialize_process \
                              -lglslang -lMachineIndependent -lOSDependent -lHLSL -lOGLCompiler -lGenericCodeGen \
-@@ -6573,11 +6573,7 @@
- # Media SDK or Intel Media Server Studio, these don't come with
+@@ -6617,15 +6617,7 @@
  # pkg-config support.  Instead, users should make sure that the build
  # can find the libraries and headers through other means.
--enabled libmfx            && { check_pkg_config libmfx "libmfx >= 1.28" "mfx/mfxvideo.h" MFXInit ||
--                               { require libmfx "mfx/mfxvideo.h mfx/mfxdefs.h" MFXInit "-llibmfx $advapi32_extralibs" &&
--                                 { test_cpp_condition mfx/mfxdefs.h "MFX_VERSION >= 1028" || die "ERROR: libmfx version must be >= 1.28"; }  &&
--                                 warn "using libmfx without pkg-config"; } }
--
-+enabled libmfx            && require libmfx "mfx/mfxvideo.h" MFXInit -lmfx && warn "using libmfx without pkg-config";
- if enabled libmfx; then
-    check_cc MFX_CODEC_VP9 "mfx/mfxvp9.h mfx/mfxstructures.h" "MFX_CODEC_VP9"
- fi
-@@ -6595,19 +6591,12 @@
+ elif enabled libmfx; then
+-    { check_pkg_config libmfx "libmfx >= 1.28 libmfx < 2.0" "mfxvideo.h" MFXInit ||
+-# Some old versions of libmfx have the following settings in libmfx.pc:
+-#   includedir=/usr/include
+-#   Cflags: -I${includedir}
+-# So add -I${includedir}/mfx to CFLAGS
+-      { check_pkg_config libmfx "libmfx >= 1.28 libmfx < 2.0" "mfx/mfxvideo.h" MFXInit && add_cflags -I${libmfx_incdir}/mfx; } ||
+-      { require libmfx "mfxvideo.h mfxdefs.h" MFXInit "-llibmfx $advapi32_extralibs" &&
+-        { test_cpp_condition mfxdefs.h "MFX_VERSION >= 1028 && MFX_VERSION < 2000" || die "ERROR: libmfx version must be >= 1.28 and < 2.0"; }  &&
+-        warn "using libmfx without pkg-config"; } } &&
++    require libmfx "mfx/mfxvideo.h" MFXInit -lmfx && warn "using libmfx without pkg-config" &&
+     warn "build FFmpeg against libmfx 1.x, obsolete features of libmfx such as OPAQUE memory,\n"\
+          "multi-frame encode, user plugins and LA_EXT rate control mode are enabled"
+ elif enabled libvpl; then
+@@ -6653,19 +6645,12 @@
                                 { check_pkg_config libopencv opencv opencv2/core/core_c.h cvCreateImageHeader ||
                                   require libopencv opencv2/core/core_c.h cvCreateImageHeader -lopencv_core -lopencv_imgproc; } ||
                                 require_pkg_config libopencv opencv opencv/cxcore.h cvCreateImageHeader; }
@@ -53,7 +58,7 @@
  enabled libplacebo        && require_pkg_config libplacebo "libplacebo >= 4.192.0" libplacebo/vulkan.h pl_vulkan_create
  enabled libpulse          && require_pkg_config libpulse libpulse pulse/pulseaudio.h pa_context_new
  enabled librabbitmq       && require_pkg_config librabbitmq "librabbitmq >= 0.7.1" amqp.h amqp_new_connection
-@@ -6623,9 +6612,9 @@
+@@ -6681,9 +6666,9 @@
  enabled libsnappy         && require libsnappy snappy-c.h snappy_compress -lsnappy -lstdc++
  enabled libsoxr           && require libsoxr soxr.h soxr_create -lsoxr
  enabled libssh            && require_pkg_config libssh libssh libssh/sftp.h sftp_init
@@ -66,7 +71,7 @@
  enabled libtensorflow     && require libtensorflow tensorflow/c/c_api.h TF_Version -ltensorflow
  enabled libtesseract      && require_pkg_config libtesseract tesseract tesseract/capi.h TessBaseAPICreate
  enabled libtheora         && require libtheora theora/theoraenc.h th_info_init -ltheoraenc -ltheoradec -logg
-@@ -6643,19 +6632,15 @@
+@@ -6701,19 +6686,15 @@
  
  enabled libvpx            && {
      enabled libvpx_vp8_decoder && {
@@ -86,26 +91,26 @@
              check_lib libvpx_vp9_encoder "vpx/vpx_encoder.h vpx/vp8cx.h" "vpx_codec_vp9_cx VPX_IMG_FMT_HIGHBITDEPTH" "-lvpx $libm_extralibs $pthreads_extralibs"
      }
      if disabled_all libvpx_vp8_decoder libvpx_vp9_decoder libvpx_vp8_encoder libvpx_vp9_encoder; then
-@@ -6664,14 +6649,14 @@
+@@ -6722,14 +6703,14 @@
  }
  
  enabled libwebp           && {
 -    enabled libwebp_encoder      && require_pkg_config libwebp "libwebp >= 0.2.0" webp/encode.h WebPGetEncoderVersion
 -    enabled libwebp_anim_encoder && check_pkg_config libwebp_anim_encoder "libwebpmux >= 0.4.0" webp/mux.h WebPAnimEncoderOptionsInit; }
 -enabled libx264           && require_pkg_config libx264 x264 "stdint.h x264.h" x264_encoder_encode &&
-+    enabled libwebp_encoder      && require libwebp webp/encode.h WebPGetEncoderVersion -lwebp
-+    enabled libwebp_anim_encoder && require libwebp_anim_encoder webp/mux.h WebPAnimEncoderOptionsInit -lwebpmux -lwebp; }
++    enabled libwebp_encoder      && require libwebp webp/encode.h WebPGetEncoderVersion -lwebp -lsharpyuv
++    enabled libwebp_anim_encoder && require libwebp_anim_encoder webp/mux.h WebPAnimEncoderOptionsInit -lwebpmux -lwebp -lsharpyuv; }
 +enabled libx264           && require libx264 "stdint.h x264.h" x264_encoder_encode -lx264 $pthreads_extralibs &&
-                              require_cpp_condition libx264 x264.h "X264_BUILD >= 118" && {
+                              require_cpp_condition libx264 x264.h "X264_BUILD >= 122" && {
                               [ "$toolchain" != "msvc" ] ||
                               require_cpp_condition libx264 x264.h "X264_BUILD >= 158"; } &&
                               check_cpp_condition libx262 x264.h "X264_MPEG2"
 -enabled libx265           && require_pkg_config libx265 x265 x265.h x265_api_get &&
 +enabled libx265           && require libx265 x265.h x265_encoder_encode -lx265 $pthreads_extralibs &&
-                              require_cpp_condition libx265 x265.h "X265_BUILD >= 70"
+                              require_cpp_condition libx265 x265.h "X265_BUILD >= 89"
  enabled libxavs           && require libxavs "stdint.h xavs.h" xavs_encoder_encode "-lxavs $pthreads_extralibs $libm_extralibs"
  enabled libxavs2          && require_pkg_config libxavs2 "xavs2 >= 1.3.0" "stdint.h xavs2.h" xavs2_api_get
-@@ -6681,7 +6666,7 @@
+@@ -6739,7 +6720,7 @@
  enabled libzvbi           && require_pkg_config libzvbi zvbi-0.2 libzvbi.h vbi_decoder_new &&
                               { test_cpp_condition libzvbi.h "VBI_VERSION_MAJOR > 0 || VBI_VERSION_MINOR > 2 || VBI_VERSION_MINOR == 2 && VBI_VERSION_MICRO >= 28" ||
                                 enabled gpl || die "ERROR: libzvbi requires version 0.2.28 or --enable-gpl."; }
@@ -114,7 +119,7 @@
  enabled mbedtls           && { check_pkg_config mbedtls mbedtls mbedtls/x509_crt.h mbedtls_x509_crt_init ||
                                 check_pkg_config mbedtls mbedtls mbedtls/ssl.h mbedtls_ssl_init ||
                                 check_lib mbedtls mbedtls/ssl.h mbedtls_ssl_init -lmbedtls -lmbedx509 -lmbedcrypto ||
-@@ -6719,15 +6704,13 @@
+@@ -6778,15 +6759,13 @@
                                 die "ERROR: OpenMAX IL headers from raspberrypi/firmware not found"; } &&
                               enable omx
  enabled omx               && require_headers OMX_Core.h
